version: "3"

services:
  cosmos:
    image: rosetta-ci:latest
    command: ["simd", "start", "--pruning", "nothing"]
    ports:
      - 9090:9090
      - 26657:26657

  rest:
    image: rosetta-ci:latest
    command: [
      "simcli",
      "rest-server",
      "--laddr", "tcp://0.0.0.0:1317",
      "--node", "tcp://cosmos:26657"
    ]
    ports:
      - 1317:1317

  rosetta:
    image: rosetta-ci:latest
    command: [
      "simcli",
      "rosetta",
      "--blockchain", "app",
      "--network", "network",
      "--tendermint-rpc", "cosmos:26657",
      "--app-rpc", "rest:1317",
      "--listen-addr", ":8080",
    ]
    ports:
      - 8080:8080

  faucet:
    image: rosetta-ci:latest
    working_dir: /rosetta
    command: ["python3", "faucet.py"]
    expose:
      - 8080

  test_rosetta:
    image: tendermintdev/rosetta-cli:v0.5.23
    volumes:
      - ./configuration:/rosetta/config:z
    command: [ "./config/run_tests.sh" ]
    working_dir: /rosetta
