name: CLI Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  protobuf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
        id: git_diff
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - name: build-sim
        run: |
          make build-sim
        if: "env.GIT_DIFF != ''"
      - name: cli-test
        run: |
          make test-integration
        if: "env.GIT_DIFF != ''"

  amino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
        id: git_diff
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - name: build-sim
        run: |
          make build-sim-amino
        if: "env.GIT_DIFF != ''"
      - name: cli-test
        run: |
          make test-integration-amino
        if: "env.GIT_DIFF != ''"
